POST https://store-maria.herokuapp.com/products
Content-Type: application/x-www-form-urlencoded

name=zapatos&price=40.50

###
GET https://store-maria.herokuapp.com/products
Accept: application/json




