POST https://store-maria.herokuapp.com/products
Content-Type: application/x-www-form-urlencoded

name=pantalon&price=3.20

###
GET https://store-maria.herokuapp.com/products
Accept: application/json



